# Generated by Django 6.0.4 on 2026-04-29 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="departement",
            field=models.CharField(
                blank=True, help_text="Pour DDS", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("USAGER", "Usager (Plaignant)"),
                    ("PFE", "Point Focal Établissement"),
                    ("DIRECTEUR_EST", "Direction de l'Établissement"),
                    ("DDS", "Direction Départementale de la Santé"),
                    ("DQSS", "DQSS / Agence Nationale Qualité"),
                    ("CABINET", "Ministère de la Santé (Cabinet)"),
                    ("AGENT_INTERNE", "Agent Affecté (Interne)"),
                    ("ADMIN_PLATEFORME", "Administrateur Plateforme"),
                ],
                default="USAGER",
                max_length=30,
            ),
        ),
    ]
