# Generated by Django 6.0.5 on 2026-05-20 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_must_change_password_and_more"),
        ("establishments", "0003_zone_sanitaire"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="zone_sanitaire",
            field=models.ForeignKey(
                blank=True,
                help_text="Zone sanitaire de compétence (pour PFZS, PNUSS niveau zone).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="agents",
                to="establishments.zonesanitaire",
                verbose_name="Zone Sanitaire",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("USAGER", "Usager (Plaignant)"),
                    ("PFE", "Point Focal Établissement"),
                    ("PFZS", "Point Focal Zone Sanitaire"),
                    ("DIRECTEUR_EST", "Établissement (Direction)"),
                    ("DDS", "Direction Départementale de la Santé (DDS)"),
                    ("DQSS", "DQSS / Agence Nationale Qualité"),
                    ("CABINET", "Ministère de la Santé (Cabinet)"),
                    ("AGENT_INTERNE", "Agent Affecté (Interne)"),
                    ("AGENT_CALL_CENTER", "Agent Call Center 136"),
                    ("PNUSS", "Représentant PNUSS"),
                    ("ADMIN_PLATEFORME", "Administrateur Plateforme"),
                ],
                default="USAGER",
                max_length=30,
            ),
        ),
    ]
