# Generated by Django 6.0.5 on 2026-06-13 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auditor_role_and_labels'),
        ('establishments', '0003_zone_sanitaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='departement',
            field=models.CharField(blank=True, help_text='Département (PF-DDS, PNUSS départemental, auditeur)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='zone_sanitaire',
            field=models.ForeignKey(blank=True, help_text='Zone sanitaire (PFZS, PNUSS zone, auditeur).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='establishments.zonesanitaire', verbose_name='Zone Sanitaire'),
        ),
    ]
