# Generated by Django 6.0.4 on 2026-04-29 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complaint",
            name="status",
            field=models.CharField(
                choices=[
                    ("SOUMISE", "Soumise"),
                    ("ACCUSEE", "Accusée de réception"),
                    ("INSTRUITE", "Instruite / Qualifiée"),
                    ("AFFECTEE", "Affectée"),
                    ("EN_TRAITEMENT", "En traitement / Investigation"),
                    ("RESOLUE", "Résolue"),
                    ("ESCALADEE", "Escaladée"),
                    ("ARBITREE", "Arbitrée"),
                    ("CLOTUREE", "Clôturée"),
                    ("REJETEE", "Rejetée"),
                ],
                default="SOUMISE",
                max_length=25,
            ),
        ),
    ]
