# Generated by Django 6.0.4 on 2026-04-29 14:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0002_alter_complaint_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="dds_assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dds_assigned_complaints",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="complaint",
            name="extension_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="complaint",
            name="extension_requested_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="complaint",
            name="resolution_accepted",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="complaint",
            name="resolution_ack_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="complaint",
            name="resolution_ack_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="complaint",
            name="resolution_validated",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="complaint",
            name="resolution_validated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="complaint",
            name="resolution_validated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="validated_resolutions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="ComplaintDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("FICHE_PLAINTE", "Fiche de plainte"),
                            ("RECEPISSE_ACCUSATION", "Récépissé accusé de réception"),
                            ("FICHE_QUALIFICATION", "Fiche de qualification"),
                            ("BON_AFFECTATION", "Bon d'affectation"),
                            ("JOURNAL_INSTRUCTION", "Journal d'instruction"),
                            ("RAPPORT_RESOLUTION", "Rapport de résolution"),
                            ("DOSSIER_ESCALADE", "Dossier d'escalade"),
                            ("DECISION_ARBITRAGE", "Décision d'arbitrage"),
                            ("FICHE_CLOTURE", "Fiche de clôture"),
                        ],
                        max_length=40,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "complaint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="complaints.complaint",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["complaint", "doc_type"],
                        name="complaints__complai_21fd55_idx",
                    )
                ],
            },
        ),
    ]
