# Generated by Django 6.0.4 on 2026-05-06 23:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def seed_priority_levels(apps, schema_editor):
    PriorityLevel = apps.get_model("complaints", "PriorityLevel")
    for code, label, hours, order in [
        ("P1", "P1 — Critique", 4, 1),
        ("P2", "P2 — Urgent", 24, 2),
        ("P3", "P3 — Élevé", 72, 3),
        ("P4", "P4 — Normal", 168, 4),
        ("P5", "P5 — Faible", 360, 5),
    ]:
        PriorityLevel.objects.get_or_create(
            code=code,
            defaults={
                "label": label,
                "hours_target": hours,
                "order": order,
                "is_active": True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        (
            "complaints",
            "0003_complaint_dds_assigned_to_complaint_extension_reason_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PriorityLevel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=5, unique=True)),
                ("label", models.CharField(max_length=120)),
                ("hours_target", models.PositiveIntegerField(default=168)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order", "code"],
            },
        ),
        migrations.CreateModel(
            name="RoleWorkflowPermission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("role", models.CharField(max_length=30, unique=True)),
                (
                    "permissions",
                    models.JSONField(
                        default=dict,
                        help_text='Ex: {"manage_documents": true, "close_complaints": true}',
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Permissions par rôle",
            },
        ),
        migrations.AddField(
            model_name="complaint",
            name="voice_file",
            field=models.FileField(
                blank=True, null=True, upload_to="complaints/voice/%Y/%m/"
            ),
        ),
        migrations.AddField(
            model_name="complaintdocument",
            name="body",
            field=models.TextField(
                blank=True, help_text="Rédaction officielle (texte)"
            ),
        ),
        migrations.AddField(
            model_name="complaintdocument",
            name="last_edited_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="edited_documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="complaintdocument",
            name="status",
            field=models.CharField(
                choices=[("DRAFT", "Brouillon"), ("SUBMITTED", "Soumis / Figé")],
                default="DRAFT",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="complaintdocument",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RunPython(seed_priority_levels, migrations.RunPython.noop),
    ]
