# Generated by Django 6.0.5 on 2026-05-20 01:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0004_operational_and_documents_priority"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="call_center_agent",
            field=models.ForeignKey(
                blank=True,
                help_text="Agent du call center ayant saisi la plainte au nom de l'usager (canal 136).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="call_center_transcribed_complaints",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Agent Call Center",
            ),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="channel",
            field=models.CharField(
                choices=[
                    ("WEB", "Portail Web"),
                    ("MOBILE", "Application Mobile"),
                    ("SMS", "SMS"),
                    ("CHATBOT", "Chatbot"),
                    ("GUICHET", "Guichet Physique"),
                    ("CALL_CENTER", "Call Center 136"),
                ],
                default="WEB",
                max_length=12,
            ),
        ),
    ]
