# Generated by Django 6.0.5 on 2026-06-18 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0010_media_url_and_file_max_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="call_center_completed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Date à laquelle l'agent call center a finalisé la plainte sociale.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="complaint",
            name="pending_call_center_completion",
            field=models.BooleanField(
                default=False,
                help_text="Vrai si la plainte a été reçue via un chatbot social et attend qu'un agent call center complète les champs manquants avant de la finaliser.",
            ),
        ),
        migrations.AddField(
            model_name="complaint",
            name="social_raw_message",
            field=models.TextField(
                blank=True,
                help_text="Message brut reçu via WhatsApp ou Facebook Messenger",
            ),
        ),
        migrations.AddField(
            model_name="complaint",
            name="social_sender_id",
            field=models.CharField(
                blank=True,
                help_text="Identifiant de l'expéditeur sur le canal social (numéro, ID FB…)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="complaint",
            name="social_source",
            field=models.CharField(
                blank=True,
                help_text="Source sociale : whatsapp | facebook | openwa | meta | …",
                max_length=20,
            ),
        ),
    ]
