# Generated by Django 6.0.5 on 2026-06-24 13:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0011_add_social_complaint_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="WhatsAppSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("phone_number", models.CharField(max_length=50, unique=True)),
                ("state", models.CharField(default="START", max_length=50)),
                ("draft_data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Session WhatsApp",
                "verbose_name_plural": "Sessions WhatsApp",
            },
        ),
    ]
