# Generated by Django 6.0.4 on 2026-05-06 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("establishments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="establishment",
            name="operational_status",
            field=models.CharField(
                choices=[
                    ("OPERATIONAL", "Opérationnel"),
                    ("LIMITED", "Service limité / partiel"),
                    ("CLOSED_TEMP", "Fermeture temporaire"),
                    ("CLOSED_PERM", "Fermeture définitive / transféré"),
                ],
                default="OPERATIONAL",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="operational_status",
            field=models.CharField(
                choices=[
                    ("OPERATIONAL", "Opérationnel"),
                    ("LIMITED", "Service limité / partiel"),
                    ("CLOSED_TEMP", "Fermeture temporaire"),
                    ("CLOSED_PERM", "Fermeture définitive / transféré"),
                ],
                default="OPERATIONAL",
                max_length=20,
            ),
        ),
    ]
