# Generated by Django 6.0.5 on 2026-05-20 01:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("establishments", "0002_operational_and_documents_priority"),
    ]

    operations = [
        migrations.CreateModel(
            name="ZoneSanitaire",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, verbose_name="Nom de la zone sanitaire"
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="Code"),
                ),
                (
                    "communes",
                    models.TextField(
                        blank=True,
                        help_text="Liste des communes couvertes, séparées par des virgules.",
                        verbose_name="Communes couvertes",
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zones_sanitaires",
                        to="establishments.region",
                        verbose_name="Département (DDS)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zone Sanitaire",
                "verbose_name_plural": "Zones Sanitaires",
                "ordering": ["region", "name"],
            },
        ),
        migrations.AddField(
            model_name="establishment",
            name="zone_sanitaire",
            field=models.ForeignKey(
                blank=True,
                help_text="Zone sanitaire à laquelle appartient cet établissement.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="establishments",
                to="establishments.zonesanitaire",
                verbose_name="Zone Sanitaire",
            ),
        ),
    ]
