# Generated by Django 6.0.5 on 2026-07-07 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("establishments", "0003_zone_sanitaire"),
    ]

    operations = [
        migrations.AddField(
            model_name="establishment",
            name="level",
            field=models.CharField(
                choices=[
                    ("PERIPHERAL", "Zone Périphérique (HZ, CS)"),
                    ("CHD", "Centre Hospitalier Départemental"),
                    ("NATIONAL", "Établissement National (CNHU, HOMEL…)"),
                ],
                default="PERIPHERAL",
                help_text="Niveau dans la pyramide sanitaire (détermine le circuit d'escalade).",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="establishment",
            name="type",
            field=models.CharField(
                choices=[
                    ("CHU", "Centre Hospitalier Universitaire (CHU/CNHU)"),
                    ("CHD", "Centre Hospitalier Départemental (CHD)"),
                    ("HZ", "Hôpital de Zone (HZ)"),
                    ("CS", "Centre de Santé (CS/CSCOM/CSA)"),
                    ("PRIVE", "Établissement Privé"),
                    ("PHARMACIE", "Pharmacie"),
                    ("LABORATOIRE", "Laboratoire"),
                ],
                max_length=20,
            ),
        ),
    ]
