# Generated by Django 6.0.5 on 2026-05-15 16:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reporter_name", models.CharField(blank=True, max_length=200)),
                ("reporter_email", models.EmailField(blank=True, max_length=254)),
                ("reporter_phone", models.CharField(blank=True, max_length=20)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("BUG", "Bug / Erreur technique"),
                            ("PERFORMANCE", "Lenteur / Performance"),
                            ("SECURITE", "Problème de sécurité"),
                            ("FONCTIONNALITE", "Fonctionnalité manquante"),
                            ("AUTRE", "Autre"),
                        ],
                        default="BUG",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField()),
                (
                    "page_url",
                    models.CharField(
                        blank=True,
                        help_text="URL ou écran où le problème est apparu",
                        max_length=500,
                    ),
                ),
                (
                    "device_info",
                    models.CharField(
                        blank=True,
                        help_text="Appareil / navigateur / version app",
                        max_length=300,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OUVERT", "Ouvert"),
                            ("EN_COURS", "En cours de traitement"),
                            ("RESOLU", "Résolu"),
                            ("FERME", "Fermé (non reproductible)"),
                        ],
                        default="OUVERT",
                        max_length=20,
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True, help_text="Notes internes de l'administrateur"
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reporter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="platform_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Signalement plateforme",
                "verbose_name_plural": "Signalements plateforme",
                "ordering": ["-created_at"],
            },
        ),
    ]
